name: cascade

channels:
  - rdkit

dependencies:
  - python=3.5
  - rdkit=2018.03.03
  - pip:
      - keras==2.2.5
      - tensorflow==1.12.0
      - tqdm==4.54.0
      - scipy==1.4.1
      - scikit-learn==0.22.2.post1
